version: '3'
services:
  mongodb-container-one:
    image: mongo:latest
    container_name: "mongodb-container"
    ports:
      - 27017:27017
  my-spring-app:
    image: my-spring-app:latest
    build: .
    ports:
      - "8081:8081"
